### ISSUE TITLE
Kotlin version of repo

### ISSUE THREAD

**Issue by pranaypatel512** [sourabhgupta811/RxRetroRealm#1]
I have update repo with kotlin in the new branch.
Please check: https://github.com/pranaypatel512/RxRetroRealm/tree/kotlin

**Comment by sourabhgupta811** [comment]
Hi @pranaypatel512 
The code looks good to me. There is just one problem. You are copying realm list twice in you getDbRepo() which publishes a duplicate list in offline mode. Just delete the code that i have highlighted in the below image and make a PR.
![image](https://user-images.githubusercontent.com/32221826/42928101-123e9e38-8b54-11e8-8734-e2f752284808.png)
